puts""
puts "Exercise No.1 - A Good First Programm"
puts "-------------------------------------"
puts ""
puts "Hello World."
puts "Hello Again."
puts "I like typing this."
puts "This is fun."
puts 'Yay! Printing.'
puts "I'd much rather you 'not'."
puts 'I "said" do not touch this.'
puts ""
puts "Extra Credit:"
puts "-------------"
puts "It's another Line"
puts "'Yeah! a new Line'"
puts "'Ho Ho Ho, but not for U Courtney!'"
puts""
puts""
puts "It's a Comment with #"
#puts "It's a Comment"
